//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Itogovaya_tochno
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Менеджер.
    /// </summary>
    // *** Start programmer edit section *** (Менеджер CustomAttributes)

    // *** End programmer edit section *** (Менеджер CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МенеджерE", new string[] {
            "ФИО as \'ФИО\'"})]
    [View("МенеджерL", new string[] {
            "ФИО as \'ФИО\'"})]
    public class Менеджер : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        // *** Start programmer edit section *** (Менеджер CustomMembers)

        // *** End programmer edit section *** (Менеджер CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Менеджер.ФИО CustomAttributes)

        // *** End programmer edit section *** (Менеджер.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Менеджер.ФИО Get start)

                // *** End programmer edit section *** (Менеджер.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Менеджер.ФИО Get end)

                // *** End programmer edit section *** (Менеджер.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Менеджер.ФИО Set start)

                // *** End programmer edit section *** (Менеджер.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Менеджер.ФИО Set end)

                // *** End programmer edit section *** (Менеджер.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МенеджерE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МенеджерE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МенеджерE", typeof(IIS.Itogovaya_tochno.Менеджер));
                }
            }
            
            /// <summary>
            /// "МенеджерL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МенеджерL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МенеджерL", typeof(IIS.Itogovaya_tochno.Менеджер));
                }
            }
        }
    }
}
